### ISSUE TITLE
version mismatch between 4.7.3 and 4.7.4

### ISSUE THREAD

**Issue by michaelkeiluweit** [OXIDprojects/oxchkversion#2]
Copied from skype protocol:

I picked one file to check the issue: application/components/widgets/oxwcookienote.php
this file has 3 different checksums since 4.7.0:
in 4.7.0, (4.7.1, 4.7.2, 4.7.3) and 4.7.4.

But the file does not appear in the update package from 4.7.3 to 4.7.4
I diffed the files and found out, that the class itself has no changes
just the header:
4.7.3:  \* @copyright OXID eSales AG 2003-2012
4.7.4:  \* @copyright OXID eSales AG 2003-2013

Those files which have no changes except the year in the header were during the building of update packages excepted. So we have some wrong version mismatches now. The oxchkversion itself is right when it says that the file is version mismatch, but all in all the file is ok, because only the year in the header was increased and no code was changed.

**Comment by ghost** [comment]
This issue is related to a known bug: https://bugs.oxid-esales.com/view.php?id=2476

**Comment by michaelkeiluweit** [comment]
was fixed a long time ago: http://forum.oxid-esales.com/showthread.php?t=14368&page=7#post121308
